version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-snmp
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-SNMP}
      MYSQL_USER: ${MYSQL_USER:-sqluser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sqluser_password}
    ports:
      - "${MYSQL_HOST_PORT:-3002}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Place ici des scripts .sql/.sh si tu veux initialiser des tables
      # - ./mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 12

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Permet de pré-sélectionner le serveur dans l’UI
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
